name: sangeet
description: A cross platform app for music streaming.
publish_to: "none"

version: 1.0.0+1


environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  animations: ^2.0.11
  app_links: ^3.5.1
  archive: ^3.1.6
  audio_service: ^0.18.17
  audio_service_mpris: ^0.1.5
  audio_video_progress_bar: ^2.0.3
  audiotags: ^1.4.1
  buttons_tabbar: ^1.3.13
  cached_network_image: ^3.4.0
  dio: ^5.7.0
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_lyric: ^2.0.4+6
  flutter_slidable: ^3.1.2
  get: ^4.7.1
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.6
  ionicons: ^0.2.2
  phosphor_flutter: ^2.1.0
  jni: ^0.14.0
  just_audio: ^0.9.46
  just_audio_media_kit:
    git:
      url: https://github.com/harshusvg/just_audio_media_kit.git
      ref: 6672eb82657d9e671abbf42122031c88aa9e6d80
  palette_generator: ^0.3.3+4
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  share_plus: ^10.1.4
  package_info_plus: ^8.0.0
  wakelock_plus: ^1.3.3
  shimmer: ^3.0.0
  sidebar_with_animation:
    git:
      url: https://github.com/harshusvg/animated_side_bar.git
      branch: main
      ref: b53567a42b4ba3793a3cf00d478bdba0ecce33d7
  smtc_windows: ^0.1.2
  terminate_restart:
    git:
      url: https://github.com/harshusvg/terminate_restart.git
      branch: main
      ref: eb505e07e11d0fe1f5c03993e707c6678428c353
  toggle_switch: ^2.1.0
  tray_manager: ^0.2.3
  url_launcher: ^6.2.1
  widget_marquee: ^0.0.8
  window_manager: ^0.4.2
  youtube_explode_dart:
    git:
      url: https://github.com/harshusvg/youtube_explode_dart.git
      ref: 1d9ec9baa806705b1d859260eeb389ec28c6b024
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  jnigen: ^0.14.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    icon_path: "assets/icons/icon.png"
  web:
    generate: true
    image_path: "assets/icons/icon.png"
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#1a1a2e"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/playlist_placeholder.jpg

